name: "ancientlives"
description: "a collection of interesting resources..."

url: "http://localhost:4000"

#paginate: 10

markdown: kramdown
permalink: "/:categories/:title"
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true    

gems:
  - jekyll-sitemap
